### ISSUE TITLE
Back up DataSpace PPPL collections

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dataspace_preservation#15]
Back up DataSpace PPPL collections after submissions in DataSpace are turned off.  

## Collections to be backed up:
- [x] Advanced Projects
- [x]  Advanced Projects - Other Projects
- [x]  Advanced Projects - Stellarators
- [x]  Advanced Projects - System Studies
- [x]  ITER and Tokamaks
- [x]  ITER and Tokamaks - PPPL Collaborations
- [x]  Spherical Torus
- [x]  Spherical Torus - MAST-U
- [x]  Spherical Torus - NSTX
- [x]  Spherical Torus - NSTX-U
- [x]  Theory
- [x]  Theory - Theory
- [x]  Theory and Computation

## Acceptance Criteria:

* Generate backups of each collection
* Transfer the backups to the DataSpace preservation bucket in AWS (details in LastPass)
* Share backups with PPPL to confirm their usefulness in the event of total disaster recovery

**Comment by carolyncole** [comment]
@kelynch can you add a link to the Theory - Theory collection.   I am not finding it.

Otherwise the rest of the collections have been put in S3.
